const productData = [
  {
    code: "GODIGIT_MOTOR_COMPREHENSIVE",
    name: "Go Digit Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_COMPREHENSIVE",
  },
  {
    code: "HDFC_ERGO_PC_COMPREHENSIVE",
    name: "Hdfc Ergo Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_PC_COMPREHENSIVE",
  },
  {
    code: "HDFC_ERGO_PC_THIRD_PARTY",
    name: "Hdfc Ergo Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_PC_THIRD_PARTY",
  },
  {
    code: "HDFC_ERGO_PC_OD_ONLY",
    name: "Hdfc Ergo Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_PC_OD_ONLY",
  },
  {
    code: "GODIGIT_MOTOR_OWN_DAMAGE",
    name: "Go Digit Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_OWN_DAMAGE",
  },
  {
    code: "GODIGIT_MOTOR_THIRD_PARTY",
    name: "Go Digit Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_THIRD_PARTY",
  },
  {
    code: "ICICI_LOMBARD_PC_COMPREHENSIVE",
    name: "Icici Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "",
  },
  {
    code: "HDFC_ERGO_TW_COMPREHENSIVE",
    name: "HDFC Ergo Two wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_TW_COMPREHENSIVE",
  },
  {
    code: "HDFC_ERGO_TW_THIRD_PARTY",
    name: "Hdfc Ergo Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_TW_THIRD_PARTY",
  },
  {
    code: "HDFC_ERGO_TW_OD_ONLY",
    name: "Hdfc Ergo Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_TW_OD_ONLY",
  },
  {
    code: "FG_MOTOR_COMPREHENSIVE_P1",
    name: "6 Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_COMPREHENSIVE_P1",
  },
  {
    code: "GODIGIT_TW_COMPREHENSIVE",
    name: "Go Digit Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_TW_COMPREHENSIVE",
  },
  {
    code: "GODIGIT_TW_OWN_DAMAGE",
    name: "Go Digit Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_TW_OWN_DAMAGE",
  },
  {
    code: "GODIGIT_TW_THIRD_PARTY",
    name: "Go Digit Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_TW_THIRD_PARTY",
  },
  {
    code: "RELIANCE_TW_COMPREHENSIVE",
    name: "Reliance Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "RELIANCE_MOTOR",
  },
  {
    code: "RELIANCE_TW_THIRD_PARTY",
    name: "Reliance Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "RELIANCE_MOTOR",
  },
  {
    code: "RELIANCE_TW_OD",
    name: "Reliance Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "",
  },
  {
    code: "FG_MOTOR_COMPREHENSIVE_P2",
    name: "Fg Motor Comprehensive P2",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_COMPREHENSIVE_P2",
  },
  {
    code: "FG_MOTOR_OD_ONLY_P1",
    name: "6 Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_OD_ONLY_P1",
  },
  {
    code: "FG_MOTOR_OD_ONLY_P2",
    name: "Fg Motor Od Only P2",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_OD_ONLY_P1",
  },
  {
    code: "FG_MOTOR_THIRD_PARTY",
    name: "6 Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_THIRD_PARTY",
  },
  {
    code: "ICICI_LOMBARD_TW_COMPREHENSIVE",
    name: "Icici Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "ICICI_LOMBARD_TW_COMPREHENSIVE",
  },
  {
    code: "ICICI_LOMBARD_PC_OD_ONLY",
    name: "Icici Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "",
  },
  {
    code: "ICICI_LOMBARD_PC_THIRD_PARTY",
    name: "Icici Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "",
  },
  {
    code: "ICICI_LOMBARD_TW_THIRD_PARTY",
    name: "Icici Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "ICICI_LOMBARD_TW_THIRD_PARTY",
  },
  {
    code: "ICICI_LOMBARD_TW_OD_ONLY",
    name: "Icici Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "ICICI_LOMBARD_TW_OD_ONLY",
  },
  {
    code: "IFFCO_TOKIO_TW_COMPREHENSIVE",
    name: "Iffco Tokio Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "",
  },
  {
    code: "RSA_MOTOR_TW_COMPREHENSIVE",
    name: "Royal Sundaram Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "IFFCO_TOKIO_TW_TP",
    name: "Iffco Tokio Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "",
  },
  {
    code: "IFFCO_TOKIO_TW_OD",
    name: "Iffco Tokio Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "",
  },
  {
    code: "RSA_MOTOR_TW_TP",
    name: "Royal Sundaram Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_TW_TP",
  },
  {
    code: "RSA_MOTOR_TW_OD",
    name: "Royal Sundaram Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_TW_OD",
  },
  {
    code: "RSA_MOTOR_TW_NEW_BUNDLED",
    name: "Royal Sundaram Two Wheeler New Bundled",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_TW_NEW_BUNDLED",
  },
  {
    code: "RSA_MOTOR_PC_COMPREHENSIVE",
    name: "Royal Sundaram Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "RSA_MOTOR_PC_OD",
    name: "Royal Sundaram Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_PC_OD",
  },
  {
    code: "RSA_MOTOR_PC_TP",
    name: "Royal Sundaram Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_PC_TP",
  },
  {
    code: "CHOLA_PC_COMPREHENSIVE",
    name: "Chola Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_PC_COMPREHENSIVE",
  },
  {
    code: "CHOLA_PC_OD_ONLY",
    name: "Chola Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_PC_OD_ONLY",
  },
  {
    code: "CHOLA_PC_THIRD_PARTY",
    name: "Chola Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_PC_THIRD_PARTY",
  },
  {
    code: "RSA_MOTOR_PC_NEW_BUNDLED",
    name: "Royal Sundaram Pvt Car New Bundled",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ROYAL_SUNDARAM",
    insurance_code: "RSA_MOTOR_PC_NEW_BUNDLED",
  },
  {
    code: "CHOLA_TW_COMPREHENSIVE",
    name: "Chola Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_TW_COMPREHENSIVE",
  },
  {
    code: "CHOLA_TW_OD_ONLY",
    name: "Chola Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_TW_OD_ONLY",
  },
  {
    code: "CHOLA_TW_THIRD_PARTY",
    name: "Chola Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "CHOLA",
    insurance_code: "CHOLA_TW_THIRD_PARTY",
  },
  {
    code: "IFFCO_TOKIO_PC_COMPREHENSIVE",
    name: "Iffco Tokio Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "IFFCO_TOKIO_PC_COMPREHENSIVE",
  },
  {
    code: "IFFCO_TOKIO_PC_OD",
    name: "Iffco Tokio Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "IFFCO_TOKIO_PC_OD",
  },
  {
    code: "IFFCO_TOKIO_PC_TP",
    name: "Iffco Tokio Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "IFFCO_TOKIO",
    insurance_code: "IFFCO_TOKIO_PC_TP",
  },
  {
    code: "FG_MOTOR_TW_COMPREHENSIVE",
    name: "6 Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "6",
    insurance_code: "FG_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_PC_COMPREHENSIVE",
    name: "Future Generali Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_PC_THIRD_PARTY",
    name: "Future Generali Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_PC_THIRD_PARTY",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_PC_OD_ONLY",
    name: "Future Generali Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_PC_OD_ONLY",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_TW_COMPREHENSIVE",
    name: "Future Generali Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_TW_OD_ONLY",
    name: "Future Generali Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_TW_OD_ONLY",
  },
  {
    code: "FUTURE_GENERALI_MOTOR_TW_THIRD_PARTY",
    name: "Future Generali Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "FG_MOTOR_1",
    insurance_code: "FUTURE_GENERALI_MOTOR_TW_THIRD_PARTY",
  },
  {
    code: "RELIANCE_PC_COMPREHENSIVE",
    name: "Reliance Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "RELIANCE_MOTOR",
  },
  {
    code: "RELIANCE_PC_THIRD_PARTY",
    name: "Reliance Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "RELIANCE_MOTOR",
  },
  {
    code: "RELIANCE_PC_OD",
    name: "Reliance Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RELIANCE_MOTOR",
    insurance_code: "RELIANCE_PC_OD",
  },
  {
    code: "SBI_MOTOR_TW_COMPREHENSIVE",
    name: "Sbi Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "SBI_MOTOR_TW_OD",
    name: "Sbi Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_TW_OD",
  },
  {
    code: "SBI_MOTOR_TW_TP",
    name: "Sbi Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_TW_TP",
  },
  {
    code: "SBI_MOTOR_PC_COMPREHENSIVE",
    name: "Sbi Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "SBI_MOTOR_PC_OD",
    name: "Sbi Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_PC_OD",
  },
  {
    code: "SBI_MOTOR_PC_TP",
    name: "Sbi Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "SBI_MOTOR",
    insurance_code: "SBI_MOTOR_PC_TP",
  },
  {
    code: "TATA_AIG_MOTOR_PC_COMPREHENSIVE",
    name: "Tata Aig Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "TATA_AIG_MOTOR_PC_OD",
    name: "Tata Aig Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_PC_OD",
  },
  {
    code: "TATA_AIG_MOTOR_PC_TP",
    name: "Tata Aig Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_PC_TP",
  },
  {
    code: "TATA_AIG_MOTOR_PC_NEW_BUNDLED",
    name: "Tata Aig Pvt Car New Bundled",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_PC_NEW_BUNDLED",
  },
  {
    code: "ICICI_TW_COMPREHENSIVE",
    name: "Bharti Axa Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BHARTI_AXA",
    insurance_code: "",
  },
  {
    code: "ICICI_PC_COMPREHENSIVE",
    name: "Icici Pc Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BHARTI_AXA",
    insurance_code: "",
  },
  {
    code: "TATA_AIG_TW_COMPREHENSIVE",
    name: "Tata Aig Tw Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_TW_OD",
    name: "Oriental Gic Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_TW_OD",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_TW_TP",
    name: "Oriental Gic Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_TW_TP",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_TW_COMPREHENSIVE",
    name: "Oriental Gic Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_TW_NEW_BUNDLED",
    name: "Oriental Gic Motor Two Wheeler New Bundled",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_TW_NEW_BUNDLED",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_PC_OD",
    name: "Oriental Gic Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_PC_OD",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_PC_TP",
    name: "Oriental Gic Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_PC_TP",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_PC_COMPREHENSIVE",
    name: "Oriental Gic Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "ORIENTAL_GIC_MOTOR_PC_NEW_BUNDLED",
    name: "Oriental Gic Motor Pvt Car New Bundled",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ORIENTAL_GIC_MOTOR",
    insurance_code: "ORIENTAL_GIC_MOTOR_PC_NEW_BUNDLED",
  },
  {
    code: "BAJAJ_PC_COMPREHENSIVE",
    name: "Bajaj Allianz General Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_PC_COMPREHENSIVE",
  },
  {
    code: "BAJAJ_PC_OD",
    name: "Bajaj Allianz General Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_PC_OD",
  },
  {
    code: "BAJAJ_PC_TP",
    name: "Bajaj Allianz General Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_PC_TP",
  },
  {
    code: "BAJAJ_TW_COMPREHENSIVE",
    name: "Bajaj Allianz General Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_TW_COMPREHENSIVE",
  },
  {
    code: "BAJAJ_TW_OD",
    name: "Bajaj Allianz General Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_TW_OD",
  },
  {
    code: "BAJAJ_TW_TP",
    name: "Bajaj Allianz General Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAJAJ_ALLIANZ_GENERAL",
    insurance_code: "BAJAJ_TW_TP",
  },
  {
    code: "HDFC_ERGO_NEW_PC_COMPREHENSIVE",
    name: "Hdfc Ergo New Pc Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_PC",
  },
  {
    code: "HDFC_ERGO_NEW_PC_THIRD_PARTY",
    name: "Hdfc Ergo New Pc Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_PC",
  },
  {
    code: "HDFC_ERGO_NEW_PC_OD_ONLY",
    name: "Hdfc Ergo New Pc Od Only",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_PC",
  },
  {
    code: "HDFC_ERGO_NEW_TW_COMPREHENSIVE",
    name: "Hdfc Ergo New Tw Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_TW",
  },
  {
    code: "HDFC_ERGO_NEW_TW_THIRD_PARTY",
    name: "Hdfc Ergo New Tw Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_TW",
  },
  {
    code: "HDFC_ERGO_NEW_TW_OD_ONLY",
    name: "Hdfc Ergo New Tw Od Only",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "HDFC_ERGO",
    insurance_code: "HDFC_ERGO_NEW_TW",
  },
  {
    code: "TD_AIG_MOTOR_OD",
    name: "Td Tata Aig Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TD_TATA_AIG",
    insurance_code: "TD_AIG_MOTOR_OD",
  },
  {
    code: "TD_AIG_MOTOR_COMP",
    name: "Td Tata Aig Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TD_TATA_AIG",
    insurance_code: "TD_AIG_MOTOR_COMP",
  },
  {
    code: "TD_AIG_MOTOR_TP",
    name: "Td Tata Aig Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TD_TATA_AIG",
    insurance_code: "TD_AIG_MOTOR_TP",
  },
  {
    code: "UNIVERSAL_SOMPO_TW_COMPREHENSIVE",
    name: "Universal Sompo Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNIVERSAL_SOMPO",
    insurance_code: "",
  },
  {
    code: "UNIVERSAL_SOMPO_TW_OD_ONLY",
    name: "Universal Sompo Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNIVERSAL_SOMPO",
    insurance_code: "",
  },
  {
    code: "UNIVERSAL_SOMPO_TW_THIRD_PARTY",
    name: "Universal Sompo Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNIVERSAL_SOMPO",
    insurance_code: "",
  },
  {
    code: "GODIGIT_MOTOR_NEW_COMPREHENSIVE",
    name: "Godigit Motor New Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_NEW_COMPREHENSIVE",
  },
  {
    code: "GODIGIT_MOTOR_NEW_OWN_DAMAGE",
    name: "Godigit Motor New Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_NEW_OWN_DAMAGE",
  },
  {
    code: "GODIGIT_MOTOR_NEW_THIRD_PARTY",
    name: "Godigit Motor New Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_MOTOR_NEW_THIRD_PARTY",
  },
  {
    code: "GODIGIT_NEW_TW_COMPREHENSIVE",
    name: "Godigit New Tw Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_NEW_TW_COMPREHENSIVE",
  },
  {
    code: "GODIGIT_NEW_TW_OWN_DAMAGE",
    name: "Godigit New Tw Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_NEW_TW_OWN_DAMAGE",
  },
  {
    code: "GODIGIT_NEW_TW_THIRD_PARTY",
    name: "Godigit New Tw Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "GO_DIGIT_MOTOR",
    insurance_code: "GODIGIT_NEW_TW_THIRD_PARTY",
  },
  {
    code: "TD_AIG_MOTOR_NB",
    name: "Td Tata Aig Two Wheeler New Bundled",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TD_TATA_AIG",
    insurance_code: "TD_AIG_MOTOR_NB",
  },
  {
    code: "RENEWAL_PC_COMPREHENSIVE",
    name: "Renewal Four Wheeler Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RENEWAL_MOTOR",
    insurance_code: "RENEWAL_PC_COMPREHENSIVE",
  },
  {
    code: "RENEWAL_PC_SAOD",
    name: "Renewal Four Wheeler Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RENEWAL_MOTOR",
    insurance_code: "RENEWAL_PC_SAOD",
  },
  {
    code: "RENEWAL_PC_SATP",
    name: "Renewal Four Wheeler Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "RENEWAL_MOTOR",
    insurance_code: "RENEWAL_PC_SATP",
  },
  {
    code: "TATA_AIG_MOTOR_TW_COMPREHENSIVE",
    name: "Tata Aig Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_TW_COMPREHENSIVE",
  },
  {
    code: "TATA_AIG_MOTOR_TW_OD",
    name: "Tata Aig Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_TW_OD",
  },
  {
    code: "TATA_AIG_MOTOR_TW_TP",
    name: "Tata Aig Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "TATA_AIG",
    insurance_code: "TATA_AIG_MOTOR_TW_TP",
  },
  {
    code: "UNITED_INDIA_PC_COMPREHENSIVE",
    name: "United India Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "UNITED_INDIA_PC_OD",
    name: "United India Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "UNITED_INDIA_PC_TP",
    name: "United India Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "UNITED_INDIA_TW_TP",
    name: "United India Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "UNITED_INDIA_TW_OD",
    name: "United India Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "UNITED_INDIA_TW_COMPREHENSIVE",
    name: "United India Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "UNITED_INDIA",
    insurance_code: "",
  },
  {
    code: "NATIONAL_PC_COMPREHENSIVE",
    name: "National Private Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_PC",
  },
  {
    code: "NATIONAL_PC_OD",
    name: "National Private Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_PC",
  },
  {
    code: "NATIONAL_PC_TP",
    name: "National Private Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_PC",
  },
  {
    code: "NATIONAL_TW_COMPREHENSIVE",
    name: "National Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_TW",
  },
  {
    code: "NATIONAL_TW_OD",
    name: "National Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_TW",
  },
  {
    code: "NATIONAL_TW_TP",
    name: "National Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "NATIONAL_INSURANCE",
    insurance_code: "NATIONAL_TW",
  },
  {
    code: "TD_BAJAJ_TW_COMPREHENSIVE",
    name: "Bagic Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_TW_COMPREHENSIVE",
  },
  {
    code: "TD_BAJAJ_TW_OD",
    name: "Bagic Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_TW_OD",
  },
  {
    code: "TD_BAJAJ_TW_TP",
    name: "Bagic Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_TW_TP",
  },
  {
    code: "TD_BAJAJ_PC_COMPREHENSIVE",
    name: "Bagic Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_PC_COMPREHENSIVE",
  },
  {
    code: "TD_BAJAJ_PC_OD",
    name: "Bagic Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_PC_OD",
  },
  {
    code: "TD_BAJAJ_PC_TP",
    name: "Bagic Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "BAGIC_MOTOR",
    insurance_code: "TD_BAJAJ_PC_TP",
  },
  {
    code: "TD_ICICI_LOMBARD_TW_COMPREHENSIVE",
    name: "Td Icici Motor Two Wheeler Comprehensive",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_TW_COMPREHENSIVE",
  },
  {
    code: "TD_ICICI_LOMBARD_TW_THIRD_PARTY",
    name: "Td Icici Motor Two Wheeler Third Party",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_TW_THIRD_PARTY",
  },
  {
    code: "TD_ICICI_LOMBARD_TW_OD_ONLY",
    name: "Td Icici Motor Two Wheeler Own Damage",
    category_code: "TWO_WHEELER_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_TW_OD_ONLY",
  },
  {
    code: "TD_ICICI_LOMBARD_PC_COMPREHENSIVE",
    name: "Td Icici Motor Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_PC_COMPREHENSIVE",
  },
  {
    code: "TD_ICICI_LOMBARD_PC_THIRD_PARTY",
    name: "Td Icici Motor Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_PC_THIRD_PARTY",
  },
  {
    code: "TD_ICICI_LOMBARD_PC_OD_ONLY",
    name: "Td Icici Motor Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "ICICI_MOTOR",
    insurance_code: "TD_ICICI_LOMBARD_PC_OD_ONLY",
  },
  {
    code: "TD_AIG_MOTOR_PC_COMPREHENSIVE",
    name: "Td Tata Aig Pvt Car Comprehensive",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TD_AIG_PC",
    insurance_code: "TD_AIG_MOTOR_PC_COMPREHENSIVE",
  },
  {
    code: "TD_AIG_MOTOR_PC_OD",
    name: "Td Tata Aig Pvt Car Own Damage",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TD_AIG_PC",
    insurance_code: "TD_AIG_MOTOR_PC_OD",
  },
  {
    code: "TD_AIG_MOTOR_PC_TP",
    name: "Td Tata Aig Pvt Car Third Party",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TD_AIG_PC",
    insurance_code: "TD_AIG_MOTOR_PC_TP",
  },
  {
    code: "TD_AIG_MOTOR_PC_NB",
    name: "Td Tata Aig Pvt Car New Bundled",
    category_code: "MOTOR_RETAIL",
    insurance_company_code: "TD_AIG_PC",
    insurance_code: "TD_AIG_MOTOR_PC_NB",
  },
];

// Mapping of insurance_company_code to insurer names (based on insurers-2025-05-28.csv)
const insurerCodeToName = {
  GO_DIGIT_MOTOR: "Go Digit General Insurance Ltd.",
  HDFC_ERGO: "HDFC ERGO General Insurance Co. Ltd.",
  ICICI_MOTOR: "ICICI Lombard General Insurance Co. Ltd.",
  RELIANCE_MOTOR: "Reliance General Insurance Co. Ltd.",
  ROYAL_SUNDARAM: "Royal Sundaram General Insurance Co. Ltd.",
  CHOLA: "Cholamandalam MS General Insurance Co. Ltd.",
  IFFCO_TOKIO: "IFFCO Tokio General Insurance Co. Ltd.",
  6: "Future Generali India Insurance Co. Ltd.", // FG_MOTOR_1 maps to code 6
  FG_MOTOR_1: "Future Generali India Insurance Co. Ltd.",
  SBI_MOTOR: "SBI General Insurance Co. Ltd.",
  TATA_AIG: "Tata AIG General Insurance Co. Ltd.",
  BHARTI_AXA: "Bharti AXA General Insurance Co. Ltd.",
  ORIENTAL_GIC_MOTOR: "The Oriental Insurance Co. Ltd.",
  BAJAJ_ALLIANZ_GENERAL: "Bajaj Allianz General Insurance Co. Ltd.",
  BAGIC_MOTOR: "Bajaj Allianz General Insurance Co. Ltd.",
  TD_TATA_AIG: "Tata AIG General Insurance Co. Ltd.",
  TD_AIG_PC: "Tata AIG General Insurance Co. Ltd.",
  UNIVERSAL_SOMPO: "Universal Sompo General Insurance Co. Ltd.",
  RENEWAL_MOTOR: "Unknown Insurer", // Placeholder, as not in insurers-2025-05-28.csv
  UNITED_INDIA: "United India Insurance Co. Ltd.",
  NATIONAL_INSURANCE: "National Insurance Co. Ltd.",
};

/**
 * Determines vehicle type and insurer details from a productCode.
 * @param {string} productCode - The product code (e.g., "RELIANCE_TW_COMPREHENSIVE", "BAJAJ_PC_COMPREHENSIVE").
 * @returns {Object} - { vehicleType: "2W" or "4W", insurerCode: string, insurerName: string }
 * @throws {Error} - If productCode is invalid or not found in product data.
 */
function getVehicleTypeAndInsurer(productCode) {
  if (!productCode || typeof productCode !== "string") {
    throw new Error("Invalid productCode: must be a non-empty string");
  }

  const product = productData.find(
    (p) => p.code.toUpperCase() === productCode.toUpperCase()
  );

  if (!product) {
    throw new Error(`Product code not found: ${productCode}`);
  }

  let vehicleType;
  if (product.category_code === "TWO_WHEELER_RETAIL") {
    vehicleType = "2W";
  } else if (product.category_code === "MOTOR_RETAIL") {
    vehicleType = "4W";
  } else {
    throw new Error(`Invalid category_code for product: ${productCode}`);
  }

  const insurerName = insurerCodeToName[product.insurance_company_code];
  if (!insurerName) {
    throw new Error(
      `Insurer name not found for insurance_company_code: ${product.insurance_company_code}`
    );
  }

  return {
    vehicleType,
    insurerCode: product.insurance_company_code,
    insurerName,
  };
}

module.exports = {
  productData,
  getVehicleTypeAndInsurer,
  insurerCodeToName, // Add this export
};
